# Generated by Django 4.0.4 on 2022-04-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_song_num_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='img_link',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
